### ISSUE TITLE
Bulk import creates duplicate entries. 

### ISSUE THREAD

**Issue by kollross** [peteeckel/netbox-plugin-dns#38] opened 2023-08-01 03:06 UTC
**Versions**
NetBox Version: 3.5.7
NetBox DNS Version: 0.18.7
Python Version: 3.9.x

**Describe the bug**
Bulk import of records creates duplicates when records are populated from the DNS Name field via python script.

**To Reproduce**
1. Add a FQDN to DNS Name field for an IP Address
2. Run the [DNS Name Record Updater] script
3. Under Netbox-DNS verify the record does in fact exit.
4. Under the Records section of Netbox-DNS do a bulk entry (I used CSV file)
5. Click submit
6. Record successfully added.
7. Clicking back under the zone, then records, you will see a duplicate entry (same name, zone, TTL, etc)

**Expected result**
Error or skip or some indication that the record already exists.

**Actual result**
Duplicate entry created.  

Running the Bulk import multiple times will result multiple duplicate entries, so I don't think this is tied to the DNS Name Record Update script.  I think the bulk just blindly imports the data.

**Comment by peteeckel** [comment] 2023-08-01 08:01
Hi @kollross, this is in fact not a bug, though it might appear to be one.

DNS records do generally not have a unique constraint, so it is perfectly OK to have the multiple identical records in the same zone. Therefore NetBox DNS does not filter duplicates of records or even reject records that are duplicated.

There are some exceptions, most notably `CNAME` and `DNAME` (which preclude any other RR type with the same name), and the so-called 'singletons' (`SOA`, `NXT` and `NSEC`, in addition to the above two), of which only one per name is permitted. Bulk import will not let you duplicate one of these.

I agree that having duplicate records is a rare requirement (think weighted round-robin-entries, for example), but as it is they are legal and so NetBox DNS does not stop you from adding them.

I see your point, however, and I'm thinking about adding an option to filter duplicates during bulk import. The functionality is not really obvious:

* We can filter records that are duplicated within the data presented for import, though that would not make much sense - if a record is duplicated within the imported data we must assume this to be intentional
* We can filter records that are already present in the NetBox DNS records table from the input data. That makes it impossible to import duplicates that are intentional, but I think we can live with that
* Duplicates that already exist will not be removed to maintain integrity of the data set

Would that help you?

For the time being you'll need to clean up your input data yourself, or do bulk imports using the API or custom scripts and check for uniqueness before you add a record.

**Comment by peteeckel** [comment] 2023-08-01 10:24
FYI: I'm just investigating a solution for this, but adding a simple check-box to the bulk import form proves surprisingly difficult with the NetBox plugin interface. Bottom line: Currently I don't see a way to override NetBox' form for bulk importing (which is required for adding a check-box) without duplicating lots of NetBox' code.

If I can't find a reasonable (and supported!) solution to add such a check-box, would you also be fine with another configuration setting `bulk_import_filter_duplicate_records`? That would enable filtering globally, not individually per import, so it would be less flexible, but at least it would provide the functionality you need.

**Comment by kollross** [comment] 2023-08-01 13:44
I'm aware you can have duplicates, though I'm not sure why, or what benefit you would ever get out of having 10 of the same records (but that's beside the point).

I think most people will use that tool for initial ingestion,  and being able to run the script multiple times, to catch up during a migration period would be useful with out creating a giant mess.

I just wish that Netbox/IPAM and Netbox-DNS was a two way street.    Changes in Netbox-DNS would present its self in IPAM.    While I understand that's difficult (having multiple A records point to the same IP) in my case that's probably >1% of the case, it makes coming up with an import strategy very difficult trying to figure if I need to update the IPAM section (so It can copy into Netbox-DNS) vs just importing into DNS.

**Comment by peteeckel** [comment] 2023-08-01 13:54
Hi @kollross, as I said, I'm completely with you and so I'm looking into ways to provide duplicate filtering as an option. It makes perfect sense to me, although it's not what the DNS spec requires and we also need to acknowledge that duplicates are a valid option and do happen, although rately.

The link between NetBox IPAM 'DNS Name' and NetBox DNS is something I would also very much like to provide. The problem here is, unfortunately, a limitation in the plugin API: We are not allowed to modify a core NetBox form, and judging from the last time I asked Jeremy about this I don't think this will change soon.

I have discussed this issue several times, and so far no one came up with a really good idea how to automatically link between IPAM and DNS without changing anything in the form for ipam.IPaddress (the obvious idea is to add a DNS record connection to the IP address while setting up the address). There are too many ways in which duplicate IP addresses (think VRF) and duplicate address records (Views) can be related.

On the other hand, the idea is and remains on my list, and I haven't given up on it. It does, however, need to be a generic solution so it at least can be configured for every possible use case. Otherwise there's still the option of using custom scripts.

**Comment by peteeckel** [comment] 2023-08-01 16:44
Hi @kollross, it seems that modifying the data for bulk import cannot be done so easily.

I just tried to impement the deduplication functionality, but the bulk import form behaves in inacceptible ways when you hand it a data set that consists of duplicates only. Instead of just closing the form it always comes back to it, just like if you just entered the header and no records.

Changing that behaviour seems to require copying and modifying larger parts of the underlying NetBox code, just like with adding the "Filter Duplicates" button. Unless the NetBox team comes up with a solution I can't see at the moment I'm afraid the deduplication of the input data is on the user for the time being.

**Comment by kollross** [comment] 2023-08-01 17:08
Understood.   I may just need to use the bulk update for CNAME, MX, TXT, etc as I know it won't cause duplicates with the "DNS Name Record Updater" script that is also populating Netbox-DNS.

Which I also found out that the "DNS Name Record Updater" is also only creates/updates records in Netbox-DNS.   If I remove an information from the DNS Host field under IPAM is doesn't actually remove it from Netbox-DNS.

**Comment by peteeckel** [comment] 2023-08-01 17:39
> Which I also found out that the "DNS Name Record Updater" is also only creates/updates records in Netbox-DNS. If I remove an information from the DNS Host field under IPAM is doesn't actually remove it from Netbox-DNS.

That's true - but the code is in `examples` for a reason :-)

You can adjust it in every way you want to - it's meant as boilerplate for your own experiments or production code. It's just not suitable for the generic case.

**Comment by commonism** [comment] 2023-08-01 19:36
I'd adjust the zone file before importing in netbox-dns.
`named-compilezone … ` will do already.

```text
@ 604800 IN SOA ns.example.org. hostmaster.example.org. 1687505670 604800 86400 2419200 604800
@ 604800 IN NS ns.example.org.
@ 604800 IN NS ns.example.org.

ns.example.org. 3600 IN A 127.0.0.1

dup.example.org 3600 IN A 127.0.0.1
dup.example.org 3600 IN A 127.0.0.1
dup.example.org 3600 IN A 127.0.0.1
dup.example.org 3600 IN A 127.0.0.1
dup.example.org 3600 IN A 127.0.0.1
```
writing to stdout here:

```
named-compilezone -s relative -o /dev/stdout example.org /tmp/example.org. 
zone example.org/IN: loaded serial 1687505670
$ORIGIN .
$TTL 604800	; 1 week
example.org		IN SOA	dns1.c0.example.org. hostmaster.example.org. (
				1687505670 ; serial
				604800     ; refresh (1 week)
				86400      ; retry (1 day)
				2419200    ; expire (4 weeks)
				604800     ; minimum (1 week)
				)
			NS	ns.example.org.
$ORIGIN example.org.
$TTL 3600	; 1 hour
ns			A	127.0.0.1
dup.example.org		A	127.0.0.1
OK

```
If you need to adjust the ttls, use dnspython to iterate the zone before named-compilezone.
Then import.

**Comment by kollross** [comment] 2023-08-01 19:49
@commonism I'm not following what you are trying accomplishing here.

**Comment by commonism** [comment] 2023-08-01 19:54
removing duplicate records from a zone.

**Comment by kollross** [comment] 2023-08-01 19:58
The duplicates are not in the zone, that is being imported.   The duplicates arise if you bulk import data from a CSV to a zone that already had records present (from either a previous import or if being populated from the DNS Host field in the IPAM).

**Comment by peteeckel** [comment] 2023-08-04 10:29
Given the fact that cleaning up the data imported in bulk is both non-intuitive and involves major effort to make it work within the limits of the NetBox plugin environment I implemented an option to tell NetBox DNS not to accept duplicate records within a zone. 

I hope that will at least remediate your worst headaches.

**Closed** 2023-08-04 10:30 UTC

**Comment by peteeckel** [comment] 2023-08-04 10:43
New release 0.18.7 contains the new option.
