### ISSUE TITLE
CNAME records fail when they begin with underscores

### ISSUE THREAD

**Issue by Matt-Heltsley** [peteeckel/netbox-plugin-dns#124] opened 2024-01-03 18:02 UTC
**Versions**
NetBox Version: 3.6.5
NetBox DNS Version: 2.4.2
Python Version: 3.8.9

**Describe the bug**
CNAME records cannot be created when they begin with underscores with the error "Not a valid DNS host name"

**To Reproduce**
1. Create a CNAME record that begins with an underscore
2. Click Create'

**Expected result**
Records to be created succesfully.

**Actual result**
The record fails with the error "Not a valid DNS host name"

**Screenshots**

**Code Examples**

**Comment by peteeckel** [comment] 2024-01-03 18:11
Hi @Matt-Heltsley, 

this is a duplicate of #116.

**Closed by peteeckel** 2024-01-03 18:11 UTC
