### ISSUE TITLE
CNAME validation error

### ISSUE THREAD

**Issue by subdriven** [peteeckel/netbox-plugin-dns#54] opened 2023-08-23 21:38 UTC
**Versions**
NetBox Version: 3.5.8
NetBox DNS Version: 0.18.10
Python Version: 3.9

**Describe the bug**
When adding a CNAME record with _ (underscores), it appears the validation doesn't pass and cannot create the entry.

**To Reproduce**
1. Go to Records > New
2. Add a new record with a Name that includes _ (underscore) in the name
3. Click Create or Create & Add Another
4. Error: Not a valid DNS host name

**Expected result**
Expect the domain to be created successfully.

**Actual result**
Error produced that the host name is not a valid DNS entry.

![image](https://github.com/peteeckel/netbox-plugin-dns/assets/5957345/73d6ae36-b866-477e-add8-cf6a51bcaa5a)

**Comment by peteeckel** [comment] 2023-08-23 21:41
This is a duplicate of #23.

**Closed by peteeckel** 2023-08-23 21:41 UTC

**Comment by subdriven** [comment] 2023-08-23 22:07
Sorry to raise a duplicate - I somehow missed #23. But I've enabled the allow_underscores as suggested in the other ticket and am still getting the error. 
![image](https://github.com/peteeckel/netbox-plugin-dns/assets/5957345/52f5c7ed-3439-4327-b035-6515c07d724d)

![image](https://github.com/peteeckel/netbox-plugin-dns/assets/5957345/64672e17-7a57-4a9b-afce-7edfccfcc3a2)

**Comment by subdriven** [comment] 2023-08-23 22:16
I did have a mistake in the above but have fixed it. However the behavior is still the same.

`PLUGINS = [ 'netbox_dns' ]

PLUGINS_CONFIG = {
    'netbox_dns': {
        'allow_underscores_in_hostnames': True,
        'tolerate_leading_underscore_types': ["TXT", "SRV", "CNAME"]
    },
}
`

**Comment by kollross** [comment] 2023-08-23 22:22
try it with out the allow_underscore line 

```
PLUGINS_CONFIG = {
     'netbox_dns': {
         'tolerate_leading_underscore_types': ["SRV", "TXT", "CNAME"],
         'enforce_unique_records': True
     }
 }
```

**Comment by subdriven** [comment] 2023-08-23 22:27
Unfortunately no, same issue.

**Comment by kollross** [comment] 2023-08-23 22:42
Did you restart netbox?

**Comment by subdriven** [comment] 2023-08-23 23:24
Sure did.
```[@netbox ~]# vim /opt/netbox/netbox/netbox/configuration.py
[@netbox ~]# systemctl restart netbox netbox-rq

**Comment by kollross** [comment] 2023-08-24 13:49
Actually I can confirm this is still a bug.   I'm getting the same result.

**Comment by kollross** [comment] 2023-08-24 13:52
I had opened an PR about this a few weeks back but it was in relation to a CNAME, not an A record.   I can confirm the CNAME function works, but not the A record.     Your filter above only applies to TXT SRV and CNAME record.

'tolerate_leading_underscore_types': ["TXT", "SRV", "CNAME"],   

You could try adding an A record to the list.

**Comment by kollross** [comment] 2023-08-24 14:08
What version of plugin do you have running?

[root@netbox] # pip3 list | grep netbox-plugin-dns

**Comment by subdriven** [comment] 2023-08-24 14:11
Running the latest: 0.18.10

**Comment by kollross** [comment] 2023-08-24 14:13
Try uninstalling the plugin and reinstalling it.

I can't duplicate this issue, running the same version with the previous config is functional.

**Comment by subdriven** [comment] 2023-08-24 14:18
Odd... pip3 is pulling in 0.17.0.
```
(venv) [root@netbox netbox]# pip3 install netbox-dns
Collecting netbox-dns
  Using cached netbox_dns-0.17.0-py3-none-any.whl (60 kB)
Requirement already satisfied: dnspython<3.0.0,>=2.2.1 in ./venv/lib/python3.9/site-packages (from netbox-dns) (2.4.2)
Installing collected packages: netbox-dns
Successfully installed netbox-dns-0.17.0
```

**Comment by subdriven** [comment] 2023-08-24 14:37
Looks like an extremely good chance I was somehow running the wrong version yet the UI said I was running the right. At any rate, stripped it all out and reinstalled via pip
```
(venv) [root@netbox netbox]# pip install netbox-plugin-dns
Requirement already satisfied: netbox-plugin-dns in /opt/netbox/venv/lib/python3.9/site-packages (0.18.10)
Requirement already satisfied: dnspython<3.0.0,>=2.2.1 in /opt/netbox/venv/lib/python3.9/site-packages (from netbox-plugin-dns) (2.4.2)
(venv) [root@netbox netbox]# python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 720, in <module>
    plugin_config: PluginConfig = plugin.config
AttributeError: module 'netbox_dns' has no attribute 'config'
...
django.core.exceptions.ImproperlyConfigured: Plugin netbox_dns does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig subclass. 
```

I'm guessing I've got something conflicting somewhere in the virtual environment and need to rip it all out?

**Comment by subdriven** [comment] 2023-08-24 14:49
Reinstalling and running the netbox upgrade script fixed the issues and now the validation works as expected. Sorry for all the run arounds @kollross and @peteeckel .

Appreciate the help & patience!
