### ISSUE TITLE
DNS Name Unexpectedly Cleared

### ISSUE THREAD

**Issue by tlskinneriv** [peteeckel/netbox-plugin-dns#190] opened 2024-03-01 14:47 UTC
**Versions**
NetBox Version: 3.7.3
NetBox DNS Version: 0.22.3
Python Version: 3.9.18

**Describe the bug**
When the IPAM Coupling feature is enabled, if a zone is not selected in the custom fields for an IP Address object, then the DNS Name property for the IP Address is cleared out. This is a reasonably unexpected behavior based on the documentation provided in the [IPAM Coupling Documentation](https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md#ipam-coupling). The logic that implements this behavior is located on [L188 of the signals.py code](https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md#ipam-coupling). I would argue that the expected behavior would be that only if a zone is selected should this plugin act upon the data in the DNS Name field and should not clear it at all. If a valid DNS record could not be created from the data in the DNS name field, then an error should be presented to the user.

**To Reproduce**
1. Enable the IPAM coupling feature
2. Navigate to an IP address
3. Edit the IP address (change any field, do not select a zone in the custom fields)
4. See that the DNS Name has been cleared for the IP

**Expected result**
DNS Name persists even if zone is unset

**Actual result**
DNS Name is cleared

**Code Examples**
```python
@receiver(pre_save, sender=IPAddress)
def ip_address_update_dns_information(instance, **kwargs):
    if not get_plugin_config("netbox_dns", "feature_ipam_coupling"):
        return

    name, ttl, disable_ptr, zone_id = ipaddress_cf_data(instance)

    if zone_id is not None: 
        instance.dns_name = f"{name}.{Zone.objects.get(pk=zone_id).name}"
    else:
        instance.dns_name = "" # <--- LOGIC DELETING DNS NAME HERE
        instance.custom_field_data["ipaddress_dns_record_name"] = None
        instance.custom_field_data["ipaddress_dns_record_ttl"] = None
        instance.custom_field_data["ipaddress_dns_record_disable_ptr"] = False
        instance.custom_field_data["ipaddress_dns_zone_id"] = None
```

**Comment by peteeckel** [comment] 2024-03-01 14:54
Hi @tlskinneriv, thanks for raising this issue. This is exaxtly why the feature is labelled 'experimental', I'm afraid :-(

>  I would argue that the expected behavior would be that only if a zone is selected should this plugin act upon the data in the DNS Name field and should not clear it at all. 

The problem is that we need to be consistent if someone first selects a DNS zone and name (which populates the `dns_name` field) and then decides that they do not want the DNS record after all and sets DNS zone or name to `None`. Should the `dns_name` field then be cleared or not ... there are arguments for both options.

I must admit that I tend to your interpretation - if IPAM Coupling is enabled, do not touch `dns_name` unless someone explicitly selects a zone and name, in which case it is populated. It's the less destructive variant, and so it should be preferred (both are bad, IMHO).

> If a valid DNS record could not be created from the data in the DNS name field, then an error should be presented to the user.

Currently the DNS name field `dns_name` is not an input field at all. This will most likely change in a future release, but that release is not planned until after NetBox 4.0 is released as it relies on some features that will (hopefully) be part of NetBox 4.0.

**Comment by tlskinneriv** [comment] 2024-03-01 15:32
> Hi @tlskinneriv, thanks for raising this issue. This is exaxtly why the feature is labelled 'experimental', I'm afraid :-(

Absolutely understand the experimental portion of it. We were experimenting with this feature and noticed the behavior, so figured I'd bring it up. 

> The problem is that we need to be consistent if someone first selects a DNS zone and name (which populates the `dns_name` field) and then decides that they do not want the DNS record after all and sets DNS zone or name to `None`. Should the `dns_name` field then be cleared or not ... there are arguments for both options.

I think at times it would be desirable to have `dns_name` filled but not coupled to a record in the plugin, especially when DNS for the IP address is not managed by data in Netbox. I agree that there should be consistency between the data in the plugin and what exists in the IP address object. However, I believe that it could be implemented differently to prevent data loss. It could be implemented such that on a save of an IP address, _if_ a zone was previously selected but is now `None`, then the object should be updated to clear the DNS name and the rest of the data. Conversely, _if_ a zone is selected and all the other pieces are there, then the `dns_name` should be updated for consistency. The quickest fix I can think of is to query for the current data in the zone field for the IP address and implement logic to compare the previous zone and "going to be saved" zone values. Something like [this implementation](https://stackoverflow.com/questions/1355150/when-saving-how-can-you-check-if-a-field-has-changed#answer-7934958) for the query is what I'm thinking.

> Currently the DNS name field `dns_name` is not an input field at all. This will most likely change in a future release, but that release is not planned until after NetBox 4.0 is released as it relies on some features that will (hopefully) be part of NetBox 4.0.

Apologies, I misunderstood the documentation. I thought that the DNS record would have been created from the data in the `dns_name` field and am now realizing its created from the custom field "Name".

**Closed** 2024-03-01 16:29 UTC
Labels: bug

**Comment by tlskinneriv** [comment] 2024-03-01 16:56
@peteeckel I did not expect such fast resolution! Thank you very much. The added code looks like it will perform as expected. Looking forward to the next release so I can ingest it in.

**Comment by peteeckel** [comment] 2024-03-01 17:01
It's such a nice evening ... 0.22.4 is out :-)
