### ISSUE TITLE
Save on record cause double save and 2 webhooks sent

### ISSUE THREAD

**Issue by MaayanPeleg** [peteeckel/netbox-plugin-dns#298] opened 2024-06-19 07:37 UTC
**Versions**
NetBox Version: 3.7.8
NetBox DNS Version: 0.22.9
Python Version: 3.10

**Describe the bug**
When a record is updated with data and tags, and I look at the webhooks sent, I receive a webhook first of the data change, then a webhook with the tag change.

**To Reproduce**
1. Got to a record object 
2. Update the record with tags and data

**Expected result**
I believe that there should only be one update and only one webhooks sent.

**Actual result**
It seems that a double update occurs, one for data and one for tags.

**Comment by peteeckel** [comment] 2024-06-19 07:41
Hi @MaayanPeleg, 

this is a duplicate auf #89.

Unfortunately it is due to a [NetBox issue|(https://github.com/netbox-community/netbox/issues/15194) that was fixed in version 4.0.5, so I don't have a chance of backporting the fix to the legacy branch for NetBox 3.

I'm sorry, but it just can't be done.

**Closed by peteeckel** 2024-06-19 07:41 UTC
Labels: bug, wontfix

**Comment by MaayanPeleg** [comment] 2024-06-19 07:47
Thank you and apologies for not noticing that this was a duplicate issue.

**Comment by peteeckel** [comment] 2024-06-19 07:56
Never mind - you're by no means the first, the issue is really ugly and hard to spot.

The only way of getting rid of it is to upgrade NetBox to 4.0.5+ (and NetBox DNS to 1.x.x for NetBox 4 support), which will solve it immediately.
