### ISSUE TITLE
Add records to dns zone in graphql

### ISSUE THREAD

**Issue by kuon** [peteeckel/netbox-plugin-dns#470] opened 2024-11-10 16:49 UTC
I am using graphql to grab DNS data from netbox DNS, and at present I have to do N queries for zones.

```
    {
      netbox_dns_zone_list {
        id
        name
        custom_fields
        default_ttl

        nameservers {
          name
        }
      }
    }
```

Then for each zone:

```
    {
      netbox_dns_record_list(filters:{zone_id: ID_FROM_PREVIOUS_QUERY}) {
        name
        custom_fields
        type
        value
        ttl
      }
    }

```

Being able to do this:

```
    {
      netbox_dns_zone_list {
        id
        name
        custom_fields
        default_ttl

        nameservers {
          name
        }
       records {
        name
        custom_fields
        type
        value
        ttl
      }
      }
    }
```

Would greatly increase performances.

**Comment by peteeckel** [comment] 2024-11-10 17:40
Hi @kuon, this is a duplicate of #450.

The relation is from record to zone, and the current implementation of Strawerry with NetBox unfortunately does not create the reverse relation. See also [this NetBox issue](https://github.com/netbox-community/netbox/issues/17242).

**Comment by kuon** [comment] 2024-11-10 17:43
I saw #450 but I didn't realize it was the same issue as I thought the relation was zone->records. But it makes sense. Sorry for the duplicate. Thanks.

**Comment by peteeckel** [comment] 2024-11-10 17:49
No problem. 

I'll have a look at it later this week, maybe it will be possible to provide a workaround until https://github.com/netbox-community/netbox/issues/17242 is resolved.

**Comment by peteeckel** [comment] 2024-11-10 18:19
I just tried it, and it is possible to use the standard Django reverse relations and rename them so they make sense in GraphQL.

Might take a couple of days because I'm quite busy atm, but it doesn't seem to be a big deal right now.

**Comment by kuon** [comment] 2024-11-10 18:20
There is no emergency, it is only performance optimization. Thank you a lot for your work.

**Comment by peteeckel** [comment] 2024-11-10 18:21
```
query MyQuery {
  netbox_dns_zone_list {
    name,
    view {name},
    records {
      name,
      type,
      value
    }
  }
}
```

```json
{
  "data": {
    "netbox_dns_zone_list": [
      {
        "name": "0.0.10.in-addr.arpa",
        "view": {
          "name": "_default_"
        },
        "records": [
          {
            "name": "@",
            "type": "NS",
            "value": "ns1.example.com."
          },
          {
            "name": "@",
            "type": "NS",
            "value": "ns2.example.com."
          },
          {
            "name": "@",
            "type": "SOA",
            "value": "ns1.example.com. hostmaster.example.com. 1722355158 172800 7200 2592000 3600"
          },
...
```

**Comment by peteeckel** [comment] 2024-11-10 18:22
I'll work trough all the relations where this makes sense, and I still need to check how it affects automatic testing.

**Closed** 2024-11-11 09:52 UTC
Labels: duplicate, enhancement
