### ISSUE TITLE
Bug? Not able to import existing [type] CNAME records. Even when the record_id is included in the CSV bulk import.

### ISSUE THREAD

**Issue by netravnen** [peteeckel/netbox-plugin-dns#237] opened 2024-04-02 21:58 UTC
**Versions**
NetBox Version: 3.7.4
NetBox DNS Version: 0.22.8
Python Version: 3.11.2

**Describe the bug**
Bulk importing a CSV file containing the ID column of prior imported records breaks/aborts as a soon as th CNAME records are encountered in the CSV file.

**To Reproduce**
1. Bulk import A, AAAA, CNAME record as _new_ records. Works. ✔️
2. _Now_ enter the IDs of the prior imported records into the CSV file.
3. Retry a bulk import. Error when encountering the CNAME record. :negative_squared_cross_mark: 
4. See error (buttom right)

**Expected result**
Record encountered with that name already existing in the DB.

**Actual result**
I expected the BULK import to update the existing records. As I included the records id in the CSV import.

**Screenshots**
N/A

**Code Examples**
N/A

**Comment by netravnen** [comment] 2024-04-02 22:00
<img width="271" alt="image" src="https://github.com/peteeckel/netbox-plugin-dns/assets/1938389/14c81c1e-d586-4524-bd94-dde0c77bb9b9">

**Comment by netravnen** [comment] 2024-04-02 22:03
| zone | view | type | name | value | ttl | disable_ptr | description | tenant | tags | status | id
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
| home.lan | Internal | CNAME | netbox | netbox.home.lan |  |  |  | Internal |  | active | 99

**Comment by netravnen** [comment] 2024-04-02 22:07
```
root@netbox1 /opt/netbox # pip3 install git+https://github.com/peteeckel/netbox-plugin-dns.git     
Collecting git+https://github.com/peteeckel/netbox-plugin-dns.git
  Cloning https://github.com/peteeckel/netbox-plugin-dns.git to /tmp/pip-req-build-l1cjnwsu
  Running command git clone --filter=blob:none --quiet https://github.com/peteeckel/netbox-plugin-dns.git /tmp/pip-req-build-l1cjnwsu
  Resolved https://github.com/peteeckel/netbox-plugin-dns.git to commit 83089f732b3b0e6d22c7509afe7d2aa1411d5bc0
```

**Comment by peteeckel** [comment] 2024-04-10 13:56
@netravnen Have you found a way to reproduce the issue so I can investigate it?

**Comment by peteeckel** [comment] 2024-04-16 13:54
@netravnen Since I cannot reproduce the problem and you don't react anymore I'm closing this issue.

Feel free to reopen it if you can single out the problem with reproducible data!

**Closed** 2024-04-16 13:54 UTC
